import { isRejectedWithValue } from '@reduxjs/toolkit';
import toast from 'react-hot-toast';

export const rtkQueryErrorLogger = (api) => (next) => (action) => {
  // RTK Query uses 'isRejectedWithValue' to identify failed API calls
  if (isRejectedWithValue(action)) {
    // Extract the specific error message generated by our backend AppError class
    const errorMsg = action.payload?.data?.message || 'An unexpected network error occurred';
    
    // Ignore 401s if you handle them via a specific auth flow, or show them
    if (action.payload?.status !== 401) {
      toast.error(errorMsg, {
        duration: 4000,
        position: 'top-right',
        style: {
          background: '#FEF2F2',
          color: '#991B1B',
          border: '1px solid #FCA5A5'
        }
      });
    }
  }

  return next(action);
};